name: Deploy Full Stack App

on:
  push:
    branches:
      - master  # Si ta branche principale est "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend  
          npm install

      - name: Run tests
        run: |
          cd backend  
          npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > my-new-key.pem
          chmod 600 my-new-key.pem

      - name: Deploy to AWS EC2
        run: |
          echo "Déploiement sur AWS EC2..."
          ssh -o StrictHostKeyChecking=no -i my-new-key.pem ubuntu@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/ubuntu/app || exit 1  # Vérifie que le répertoire existe
            git pull origin master || exit 1  # Assure-toi que git pull fonctionne
            
            # Installer les dépendances pour chaque service
            cd backend || exit 1
            npm install || exit 1
            cd ../frontend || exit 1
            npm install || exit 1
            
            # Redémarrer l'application avec PM2
            cd /home/ubuntu/app/backend || exit 1
            pm2 restart all || pm2 start app.js
          EOF

      - name: Migrate Database on RDS
        env:
          PGPASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Exécution des migrations sur PostgreSQL RDS..."
          psql -h ${{ secrets.DB_HOST }} -U ${{ secrets.DB_USER }} -d ${{ secrets.DB_NAME }} -f backend/migrations.sql